### ISSUE TITLE
Rust build won't link on Alpine Linux

### ISSUE THREAD

**Issue by rdbo** [rdbo/libmem#166]
Add the following to your `.cargo/config.toml`:
```toml
[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=-crt-static"]
```
